apiVersion: v1
items:
  
- kind: DeploymentConfig
  apiVersion: "v1"
  metadata:
    annotations:
      description: Defines how to deploy the Airflow scheduler
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: 'airflow-scheduler'
  spec:
    replicas: 1
    selector:
      name: 'airflow-scheduler'
    strategy: 
        type: 'Rolling'
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds:
            
    template:
      metadata:
        labels:
          name: 'airflow-scheduler'
        name: 'airflow-scheduler'
      spec:
        containers:
          - env:
            - name: AIRFLOW_CMD
              value: scheduler

            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  key: database-connection-string
                  name: airflow-secrets-celery
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: database-connection-string
                  name: airflow-redis-secrets-celery
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: AIRFLOW__CORE__EXECUTOR
              value: 'CeleryExecutor'
            image: ''
            
            name: 'airflow-scheduler'
            
            resources:
              limits:
                memory: '512Mi'

            volumeMounts:
              - mountPath: /usr/local/app
                name: 'airflow-data'
        serviceAccountName: airflow-celery
        serviceAccount: airflow-celery
        volumes:
          - name: 'airflow-data'
            persistentVolumeClaim:
              claimName: 'airflow-celery'

    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - 'airflow-scheduler'
          from:
            kind: ImageStreamTag
            name: 'airflow:celery'
        type: ImageChange
      - type: ConfigChange

      
kind: List
metadata: []