apiVersion: v1
items:
- kind: Secret
  apiVersion: "v1"
  metadata:
    name: 'airflow-secrets-celery'
  stringData:
    database-user: airflow
    database-password: airflow
    database-connection-string: postgresql+psycopg2://airflow:airflow@postgresql-celery.airflow-celery.svc:5432/root 
  
- kind: Secret
  apiVersion: "v1"
  metadata:
    name: 'airflow-redis-secrets-celery'
  stringData:
    database-password: redispass
    database-connection-string: redis://:redispass@redis.airflow-celery.svc:6379/1


kind: List
metadata: []
