apiVersion: v1
items:
- kind: DeploymentConfig
  apiVersion: "v1"
  metadata:
    annotations:
      description: Defines how to deploy the database
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: 'postgresql'
  spec:
    replicas: 1
    selector:
      name: 'postgresql'
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: 'postgresql'
        name: 'postgresql'
      spec:
        containers:
          - env:
              - name: POSTGRESQL_USER
                valueFrom:
                  secretKeyRef:
                    key: database-user
                    name: airflow-secrets
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: database-password
                    name: airflow-secrets
              - name: POSTGRESQL_DATABASE
                value: 'root'
              - name: POSTGRESQL_MAX_CONNECTIONS
                value: '50'
              - name: POSTGRESQL_SHARED_BUFFERS
                value: '12MB'
            image: ' '
            livenessProbe:
              initialDelaySeconds: 30
              tcpSocket:
                port: 5432
              timeoutSeconds: 1
            name: postgresql
            ports:
              - containerPort: 5432
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-i'
                  - '-c'
                  - >-
                    psql -h 127.0.0.1 -U ${POSTGRESQL_USER} -q -d
                    root -c 'SELECT 1'
              initialDelaySeconds: 5
              timeoutSeconds: 1
            resources:
              limits:
                memory: '512Mi'
            volumeMounts:
              - mountPath: /var/lib/pgsql/data
                name: 'postgresql-data'
        volumes:
          - name: 'postgresql-data'
            persistentVolumeClaim:
              claimName: 'postgresql'
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - postgresql
          from:
            kind: ImageStreamTag
            name: 'postgresql:10'
            namespace: 'openshift'
        type: ImageChange
      - type: ConfigChange
        
- kind: Service
  apiVersion: "v1"
  metadata:
    annotations:
      description: Exposes the database server
    name: 'postgresql'
  spec:
    ports:
      - name: 'postgresql'
        port: 5432
        targetPort: 5432
    selector:
      name: 'postgresql'
      
kind: List
metadata: []