apiVersion: v1
items:

- kind: PersistentVolumeClaim
  apiVersion: "v1"
  metadata:
    name: 'postgresql-celery'
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '1Gi'

- kind: PersistentVolumeClaim
  apiVersion: "v1"
  metadata:
    name: 'airflow-celery'
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: '1Gi'
            
kind: List
metadata: []