apiVersion: v1
kind: List
items:

- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "redis-image" 
  spec:
    
    runPolicy: "Serial" 
    
    triggers:
      - type: ConfigChange
      - github:
          secret: airflow
        type: GitHub    
    
    source: 
      git:
        uri: "https://github.com/reachnaveen/openshift-redis.git"
        ref: "master"
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: true
        
    output:
      to:
        kind: ImageStreamTag
        name: 'redis:celery'

- kind: ImageStream
  apiVersion: "v1"
  metadata:
    annotations:
      description: Fedora 28 based Apache redis image
      tags: fedora, redis
    name: 'redis'