apiVersion: v1
items:

- kind: PersistentVolumeClaim
  apiVersion: "v1"
  metadata:
    name: 'postgresql'
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '1Gi'

- kind: PersistentVolumeClaim
  apiVersion: "v1"
  metadata:
    name: 'airflow'
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: '1Gi'
            
kind: List
metadata: []