apiVersion: v1
items:
  
- kind: DeploymentConfig
  apiVersion: "v1"
  metadata:
    annotations:
      description: Defines how to deploy the Airflow webserver
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: 'airflow-webserver'
  spec:
    replicas: 1
    selector:
      name: 'airflow-webserver'
    strategy: 
        type: 'Rolling'
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds:
            
    template:
      metadata:
        labels:
          name: 'airflow-webserver'
        name: 'airflow-webserver'
      spec:
        containers:
          - env:
            - name: AIRFLOW_CMD
              value: webserver

            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  key: database-connection-string
                  name: airflow-secrets

            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'

            image: ''
            
            ports:
              - containerPort: 8080
              
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 240
              periodsSeconds: 60
          
            name: 'airflow-webserver'
            
            resources:
              limits:
                memory: '512Mi'

            volumeMounts:
              - mountPath: /usr/local/app
                name: 'airflow-data'

        volumes:
          - name: 'airflow-data'
            persistentVolumeClaim:
              claimName: 'airflow'

    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - 'airflow-webserver'
          from:
            kind: ImageStreamTag
            name: 'airflow:1.10.11'
        type: ImageChange
      - type: ConfigChange

- kind: Service
  apiVersion: "v1"
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"name": "postgresql", "kind": "Service"}]'
    name: 'airflow-webserver'
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      name: 'airflow-webserver'

kind: List
metadata: []