apiVersion: v1
kind: List
items:

- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "airflow-image" 
  spec:
    
    runPolicy: "Serial" 
    
    triggers:
      - type: ConfigChange
      - github:
          secret: airflow
        type: GitHub
    
    source: 
      git:
        uri: "https://github.com/reachnaveen/openshift-airflow-celery.git"
        ref: "master"
      contextDir: "airflow"
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: true
        
    output:
      to:
        kind: ImageStreamTag
        name: 'airflow:celery'

- kind: ImageStream
  apiVersion: "v1"
  metadata:
    annotations:
      description: Fedora 28 based Apache Airflow image
      tags: fedora, airflow
    name: 'airflow'