apiVersion: v1
items:

- kind: Route
  apiVersion: "v1"
  metadata:
    name: 'airflow'
    annotations:
      kubernetes.io/tls-acme: "true"
  spec:
    host: 'airflow.stufff.review'
    to:
      kind: Service
      name: 'airflow-webserver'
    port:
      targetPort: web

kind: List
metadata: []