apiVersion: v1
items:
- kind: Secret
  apiVersion: "v1"
  metadata:
    name: 'airflow-secrets'
  stringData:
    database-user: airflow
    database-password: airflow
    database-connection-string: postgresql+psycopg2://airflow:airflow@postgresql.airflow.svc:5432/root 
  
kind: List
metadata: []
